name: Deploy Cloud Run Job

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Mantendo a configuração dos secrets
    environment: gcp-prod 

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }} 
      REGION: us-central1
      REPO_NAME: pdm-especulacoes-imobiliarias
      IMAGE_NAME: populator
      JOB_NAME: job-populate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # --- CORREÇÃO AQUI ---
      # Mudamos de "task/" para "." (ponto)
      # O ponto indica que o Dockerfile está na raiz do repositório
      - name: Build and Push Container
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Update Cloud Run Job
        run: |
          gcloud run jobs update ${{ env.JOB_NAME }} \
            --image us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }}
